### ISSUE TITLE
This already exists; for free.

### ISSUE THREAD

**Issue by MistressPlague** [Dextroo/DexProtectUnlock#1]
You literally just copied an existing project by me and another for free, that needs no mods either; meaning even streamers can use it.

https://github.com/MistressPlague/GTAnti-Rip / https://github.com/rygo6/GTAvaCrypt

**Comment by Dextroo** [comment]
This system does not use the same method as the shader-based protection in GTAvaCrypt/GTAnti-Rip and none of the code used in that project is in my tool. If you'd like to discuss this further please add me at Dextro#0001.

**Comment by MistressPlague** [comment]
It literally would not be able to sync being fixed for other players without using either parameters & shaders or OSC.

**Comment by MistressPlague** [comment]
From looking; uses params in animator; same premise.
Furthermore, it has a major flaw. One could barely modify the mod code to use any locked avatar from what I see with seconds of bruteforcing.

**Comment by MistressPlague** [comment]
Also, "key is never exposed to remote users" -> Do you not know how AssetBundles are instantiated? Yes, it is exposed, just only technical wise. One could code a mod/client to read it fully.

**Comment by MistressPlague** [comment]
I would have no issue if this project if you weren't charging more than 90% of scripts/mods for something already out and done equiv/better.

But you are, bringing major attention to me and other devs to show how flawed this is.

**Comment by Dextroo** [comment]
I'm not going to go into details about how exactly everything works, but you are making some incorrect assumptions about my tool. All I will say is if you are concerned about security, I invite you to take a look at a protected model and try to reverse it yourself. I can provide you with one via Discord if you like. Issue closed.

**Comment by MistressPlague** [comment]
Sure, send one along; or load in-game with me and I'll have it un-done in no time. 
All one would need to steal this is a basic mod to read animator params and save them to a config & re-apply and reuploadermod.

This is not secure.

**Comment by MistressPlague** [comment]
Conclusion: Attempted to fake the security to me by making me have to bruteforce keys only, not the actual thing that would happen which would be:

-User is in-lobby with unlocked avatar to use it
-Bad actor is in-lobby, too.
-Bad actor reads keys aka params via mod and exports them to a json
-Bad actor reuploads the avatar, or goes through hotswapping or alike.
-Bad actor inputs said parameters seen in json, bypassing this security fully.

Instead they only gave the bruteforcing option, which would only ever happen if someone leaked the vrca in a discord to be un-done, which is a beyond rare occurrence. This would not occur typically; what i listed above would, and this security would do nothing to stop it.

They ended the talk saying it's "draining"; considering you're charging 40 a pop for something that already exists without the need for a mod; you don't have the liberty to use that excuse for giving unrealistic bounty scenarios.

I will be posting of this majorly publicly along with many streamers becoming aware of this scandal soon; labeling how it is near-theft of money from people.

I may also look into a takedown request based on design matchings, which would apply due to the obtained patential ownings of our project.

Not a great person to ever look at buying from.
